### PR TITLE
By doing this you actually get a download instead of simply text

### PR DESCRIPTION
**Pull request by NiLSPACE**
It is however seen as a html file, so you'll have to change the extension

### CODE REVIEW

**Comment by madmaxoft** [comment]
The proper way to do this would be via HTTP headers, those could set the name and extension correctly, but there's currently no way of doing this in Cuberite, so this is the next best thing. I'm wondering though, if you put a filename into the `download` attribute, will it set the filename for the download? Why else would it be an attribute?

**Comment by NiLSPACE** [comment]
I'll try to see what it does :)

**Comment by NiLSPACE** [comment]
Oh, it actually works :O I'll update the PR :)

**Comment by NiLSPACE** [comment]
Done. If you want to combine these could you perhaps try it? Every time I try to do something a little more advanced than just adding commits and pushing things get weird.

**Comment by madmaxoft** [comment]
Thanks for the idea and the code, I eventually rewrote too much of the neighboring code so I couldn't merge this PR, I instead integrated your code directly.

**Pull request closed without merging**
